spring:
  application:
    name: usuario-query
  data:
    mongodb:
      host: localhost
      port: 27017
      database: contas
security:
  oauth2:
    resource:
      jwt:
        key-value: pedidoSigningKey

server:
  port: 10002
